apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-deployment
  labels:
    app: pytorch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pytorch
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      containers:
      - name: pytorch-container
        image: pytorch/pytorch:latest
        command: ["python", "-m", "torch.distributed.launch", "--nproc_per_node=2", "model.py"]
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        ports:
        - containerPort: 5000
